
use kaysha;

drop table if exists motivation;

CREATE TABLE motivation (
  id BIGINT AUTO_INCREMENT,
  quote VARCHAR(100) NULL,
  PRIMARY KEY (id));
  
insert into motivation(quote) values ("Either you run the day or the day runs you.");
insert into motivation(quote) values ("We make the world we live in and shape our own environment.");
insert into motivation(quote) values ("What you do today can improve all your tomorrows.");
insert into motivation(quote) values ("Wherever you are - be all there.");
insert into motivation(quote) values ("Keep going. Be all in.");
insert into motivation(quote) values ("Fight till the last gasp.");
insert into motivation(quote) values ("No guts, no story.");
insert into motivation(quote) values ("If you want it, work for it.");
insert into motivation(quote) values ("Impossible is for the unwilling.");
insert into motivation(quote) values ("Whatever you are, be a good one.");
insert into motivation(quote) values ("Take the risk or lose the chance.");
insert into motivation(quote) values ("Do it with passion or not at all.");
insert into motivation(quote) values ("Good things happen to those who hustle.");
insert into motivation(quote) values ("At the end of hardship comes happiness.");
insert into motivation(quote) values ("If it matters to you, you’ll find a way.");
insert into motivation(quote) values ("Whatever you do, do with all your might.");
insert into motivation(quote) values ("You can do anything you set your mind to.");
insert into motivation(quote) values ("Open your mind. Get up off the couch. Move.");
insert into motivation(quote) values ("In life you need either inspiration or desperation.");
insert into motivation(quote) values ("Persistence guarantees that results are inevitable.");
insert into motivation(quote) values ("Go forth on your path, as it exists only through your walking.");
insert into motivation(quote) values ("Let him that would move the world first move himself.");
insert into motivation(quote) values ("It does not matter how slowly you go as long as you do not stop.");
insert into motivation(quote) values ("Life is fragile. We’re not guaranteed a tomorrow so give it everything you’ve got.");
insert into motivation(quote) values ("It is better to live one day as a lion, than a thousand days as a lamb.");
insert into motivation(quote) values ("Fall seven times, stand up eight.");
insert into motivation(quote) values ("The two most important days in your life are the day you are born and they day you find out why.");
insert into motivation(quote) values ("Today I will do what others won’t, so tomorrow I can accomplish what others can’t.");
insert into motivation(quote) values ("Do something today that your future self will thank you for.");
insert into motivation(quote) values ("We are what we repeatedly do. Excellence then is not an act but a habit.");
insert into motivation(quote) values ("No matter how slow you go, you are still lapping everybody on the couch.");
insert into motivation(quote) values ("Sweat is fat crying.");
insert into motivation(quote) values ("You miss 100% of the shots you don’t take.");
insert into motivation(quote) values ("The difference between the impossible and the possible lies in a person’s determination.");
insert into motivation(quote) values ("If you want something you’ve never had, you must be willing to do something you’ve never done.");
insert into motivation(quote) values ("To give anything less than your best is to sacrifice the gift.");
insert into motivation(quote) values ("You’re only one workout away from a good mood.");
insert into motivation(quote) values ("Nothing will work unless you do.");
insert into motivation(quote) values ("Life begins at the end of your comfort zone.");
insert into motivation(quote) values ("I’ve failed over and over and over again in my life. And that is why I succeed.");
insert into motivation(quote) values ("Strength does not come from physical capacity. It comes from an indomitable will.");
insert into motivation(quote) values ("The difference between try and triumph is a little ‘umph’.");
insert into motivation(quote) values ("Most people lack having the guts to go on and just say they’ll go through the pain no matter what.");
insert into motivation(quote) values ("Don’t count the days, make the days count.");
insert into motivation(quote) values ("Making excuses burns zero calories per hour.");
insert into motivation(quote) values ("If you’re tired of starting over, stop giving up.");
insert into motivation(quote) values ("When you feel like quitting, think about why you started.");
insert into motivation(quote) values ("Do what you have to do until you can do what you want to do.");
insert into motivation(quote) values ("Create healthy habits, not restrictions.");
insert into motivation(quote) values ("Don’t let the scale define you. Be active, be healthy, be happy.");
insert into motivation(quote) values ("It’s going to be a journey. It’s not a sprint to get in shape.");
insert into motivation(quote) values ("No matter how slow you progress, you are still way ahead of everyone who isn’t trying.");
insert into motivation(quote) values ("Just believe in yourself. Even if you don’t pretend that you do and, and some point, you will.");
insert into motivation(quote) values ("Strive for progress, not perfection.");
insert into motivation(quote) values ("All great achievements require time.");
insert into motivation(quote) values ("We cannot start over. But we can begin now and make a new ending.");
insert into motivation(quote) values ("No pain, no gain. Shut up and train.");
insert into motivation(quote) values ("Your body can stand almost anything. It’s your mind that you have to convince.");
insert into motivation(quote) values ("Success isn’t always about greatness. Consistent hard work gains success. Greatness will come.");
insert into motivation(quote) values ("Train insane or remain the same.");
insert into motivation(quote) values ("Definition of a really good workout: when you hate doing it, but you love finishing it.");
insert into motivation(quote) values ("Push yourself because no one else is going to do it for you.");
insert into motivation(quote) values ("Suck it up. And one day you won’t have to suck it in.");
insert into motivation(quote) values ("Success starts with self-discipline.");
insert into motivation(quote) values ("Good things come to those who sweat.");
insert into motivation(quote) values ("Motivation is what gets you started. Habit is what keeps you going.");
insert into motivation(quote) values ("A one hour workout is 4% of your day. No excuses.");
insert into motivation(quote) values ("The body achieves what the mind believes.");
insert into motivation(quote) values ("What seems impossible today will one day become your warm-up.");
insert into motivation(quote) values ("Never give up on a dream just because of the time it will take to accomplish it. The time will pass.");
insert into motivation(quote) values ("Someone busier than you is working out right now.");
insert into motivation(quote) values ("Hustle for that muscle.");
insert into motivation(quote) values ("Work hard in silence. Let success be your noise.");
insert into motivation(quote) values ("The hardest lift of all is lifting your butt off the couch.");
insert into motivation(quote) values ("If you still look good at the end of your workout, you didn’t train hard enough.");
insert into motivation(quote) values ("When you feel like quitting think about why you started.");
insert into motivation(quote) values ("A good workout is when you make your dry fit shirt look like false advertising.");
insert into motivation(quote) values ("I only start counting sit-ups when it starts hurting because they’re the only ones that count.");
insert into motivation(quote) values ("It comes down to one simple thing: how bad do you want it?");
insert into motivation(quote) values ("Obstacles can’t stop you. Problems can’t stop you. People can’t stop you. Only you can stop you.");
insert into motivation(quote) values ("The only bad workout is the one that didn’t happen.");
insert into motivation(quote) values ("Exercise is like telling your body 'you’re gonna hate me for this, but you’ll thank me later.'");
insert into motivation(quote) values ("The pain you feel today, will be the strength you feel tomorrow.");
insert into motivation(quote) values ("Don’t limit your challenges, challenge your limits.");
insert into motivation(quote) values ("It’s actually pretty simple. Either you do it, or you don’t.");
insert into motivation(quote) values ("Know that there is something inside of you that is greater than any obstacle.");
insert into motivation(quote) values ("Nothing truly great ever came from a comfort zone.");
insert into motivation(quote) values ("You don’t have to be extreme, just consistent.");
insert into motivation(quote) values ("Less sugar, more fruit. Less soda, more water. Less driving, more walking. Less words, more action.");
insert into motivation(quote) values ("The difference between wanting and achieving is discipline.");
insert into motivation(quote) values ("The hard part isn’t getting your body in shape. The hard part is getting your mind in shape.");
insert into motivation(quote) values ("Remember, Rome wasn’t built in a day. Work hard, good results will come.");
insert into motivation(quote) values ("Sticks and stones may break my bones but squats will make me badass");
insert into motivation(quote) values ("Wake up. Work out. Look hot. Kick ass.");
insert into motivation(quote) values ("Go the extra mile. It’s never crowded.");
insert into motivation(quote) values ("I may not be there yet, but I’m closer than I was yesterday.");
insert into motivation(quote) values ("Don’t wish for a good body, work for it.");
insert into motivation(quote) values ("Don’t be afraid of being a beginner.");
insert into motivation(quote) values ("First they will laugh. Then they will copy. Don’t give up.");
insert into motivation(quote) values ("Sweat is magic. Cover yourself in it daily to grant your wishes.");
insert into motivation(quote) values ("Sore. The most satisfying pain.");
insert into motivation(quote) values ("70% of people that start a fitness plan quit. Except you. Not this time.");

select * from motivation;